import type { Video, Game, AnalyticsData, Language } from "@/types";

export const SUBJECTS = ["Mathematics", "Science", "Language Arts", "Social Studies", "Environmental Studies", "Art & Craft"];
export const GRADES = ["Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6"];

export const VIDEOS: Video[] = [
  {
    id: "v1",
    title: "Counting Numbers 1 to 20",
    titleHi: "1 से 20 तक गिनती",
    titleKn: "1 ರಿಂದ 20 ರವರೆಗೆ ಎಣಿಕೆ",
    description: "Learn to count from 1 to 20 with fun animations and songs.",
    descriptionHi: "मजेदार एनिमेशन और गानों के साथ 1 से 20 तक गिनना सीखें।",
    descriptionKn: "ಮೋಜಿನ ಅನಿಮೇಷನ್ ಮತ್ತು ಹಾಡುಗಳೊಂದಿಗೆ 1 ರಿಂದ 20 ರವರೆಗೆ ಎಣಿಸಲು ಕಲಿಯಿರಿ.",
    language: "en",
    subject: "Mathematics",
    grade: "Grade 1",
    thumbnailUrl: "https://picsum.photos/seed/math-counting-numbers/640/360",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    duration: 480,
    views: 3241,
    avgWatchDuration: 312,
    createdAt: "2026-01-15",
    tags: ["numbers", "counting", "grade1", "math"],
  },
  {
    id: "v2",
    title: "Plants and Their Parts",
    titleHi: "पौधे और उनके भाग",
    titleKn: "ಸಸ್ಯಗಳು ಮತ್ತು ಅವುಗಳ ಭಾಗಗಳು",
    description: "Explore the different parts of a plant - roots, stem, leaves, and flowers.",
    descriptionHi: "पौधे के विभिन्न भागों की खोज करें - जड़, तना, पत्तियां और फूल।",
    descriptionKn: "ಸಸ್ಯದ ವಿವಿಧ ಭಾಗಗಳನ್ನು ಅನ್ವೇಷಿಸಿ - ಬೇರುಗಳು, ಕಾಂಡ, ಎಲೆಗಳು ಮತ್ತು ಹೂವುಗಳು.",
    language: "en",
    subject: "Science",
    grade: "Grade 2",
    thumbnailUrl: "https://picsum.photos/seed/science-plants-nature/640/360",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    duration: 540,
    views: 2187,
    avgWatchDuration: 420,
    createdAt: "2026-01-22",
    tags: ["plants", "science", "nature", "grade2"],
  },
  {
    id: "v3",
    title: "ಕನ್ನಡ ಅಕ್ಷರಮಾಲೆ",
    titleHi: "कन्नड़ वर्णमाला",
    titleKn: "ಕನ್ನಡ ಅಕ್ಷರಮಾಲೆ",
    description: "Learn the Kannada alphabet with pronunciation and examples.",
    descriptionHi: "उच्चारण और उदाहरणों के साथ कन्नड़ वर्णमाला सीखें।",
    descriptionKn: "ಉಚ್ಚಾರಣೆ ಮತ್ತು ಉದಾಹರಣೆಗಳೊಂದಿಗೆ ಕನ್ನಡ ಅಕ್ಷರಮಾಲೆ ಕಲಿಯಿರಿ.",
    language: "kn",
    subject: "Language Arts",
    grade: "Grade 1",
    thumbnailUrl: "https://picsum.photos/seed/kannada-alphabet-letters/640/360",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    duration: 620,
    views: 4512,
    avgWatchDuration: 510,
    createdAt: "2026-02-05",
    tags: ["kannada", "alphabet", "language", "grade1"],
  },
  {
    id: "v4",
    title: "हिंदी वर्णमाला",
    titleHi: "हिंदी वर्णमाला",
    titleKn: "ಹಿಂದಿ ವರ್ಣಮಾಲೆ",
    description: "Learn the Hindi alphabet with fun pronunciation exercises.",
    descriptionHi: "मजेदार उच्चारण अभ्यास के साथ हिंदी वर्णमाला सीखें।",
    descriptionKn: "ಮೋಜಿನ ಉಚ್ಚಾರಣೆ ಅಭ್ಯಾಸಗಳೊಂದಿಗೆ ಹಿಂದಿ ವರ್ಣಮಾಲೆ ಕಲಿಯಿರಿ.",
    language: "hi",
    subject: "Language Arts",
    grade: "Grade 1",
    thumbnailUrl: "https://picsum.photos/seed/hindi-alphabet-learning/640/360",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    duration: 590,
    views: 3876,
    avgWatchDuration: 465,
    createdAt: "2026-02-10",
    tags: ["hindi", "alphabet", "language", "grade1"],
  },
  {
    id: "v5",
    title: "Our Environment",
    titleHi: "हमारा पर्यावरण",
    titleKn: "ನಮ್ಮ ಪರಿಸರ",
    description: "Understanding our environment and how to protect it.",
    descriptionHi: "हमारे पर्यावरण को समझना और उसकी रक्षा कैसे करें।",
    descriptionKn: "ನಮ್ಮ ಪರಿಸರವನ್ನು ಅರ್ಥ ಮಾಡಿಕೊಳ್ಳುವುದು ಮತ್ತು ಅದನ್ನು ಹೇಗೆ ರಕ್ಷಿಸುವುದು.",
    language: "en",
    subject: "Environmental Studies",
    grade: "Grade 3",
    thumbnailUrl: "https://picsum.photos/seed/environment-nature-earth/640/360",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    duration: 720,
    views: 1654,
    avgWatchDuration: 580,
    createdAt: "2026-02-18",
    tags: ["environment", "nature", "evs", "grade3"],
  },
  {
    id: "v6",
    title: "Simple Addition",
    titleHi: "सरल जोड़",
    titleKn: "ಸರಳ ಸೇರ್ಪಡೆ",
    description: "Learn basic addition with visual aids and practice problems.",
    descriptionHi: "दृश्य सहायता और अभ्यास समस्याओं के साथ बुनियादी जोड़ सीखें।",
    descriptionKn: "ದೃಶ್ಯ ಸಾಧನಗಳು ಮತ್ತು ಅಭ್ಯಾಸ ಸಮಸ್ಯೆಗಳೊಂದಿಗೆ ಮೂಲ ಸೇರ್ಪಡೆ ಕಲಿಯಿರಿ.",
    language: "en",
    subject: "Mathematics",
    grade: "Grade 1",
    thumbnailUrl: "https://picsum.photos/seed/math-addition-classroom/640/360",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    duration: 510,
    views: 2943,
    avgWatchDuration: 390,
    createdAt: "2026-03-01",
    tags: ["addition", "math", "grade1", "arithmetic"],
  },
  {
    id: "v7",
    title: "Animals and Their Habitats",
    titleHi: "जानवर और उनके आवास",
    titleKn: "ಪ್ರಾಣಿಗಳು ಮತ್ತು ಅವುಗಳ ಆವಾಸಸ್ಥಾನ",
    description: "Discover where different animals live and why they live there.",
    descriptionHi: "जानें कि विभिन्न जानवर कहाँ रहते हैं और क्यों रहते हैं।",
    descriptionKn: "ವಿವಿಧ ಪ್ರಾಣಿಗಳು ಎಲ್ಲಿ ವಾಸಿಸುತ್ತವೆ ಮತ್ತು ಏಕೆ ವಾಸಿಸುತ್ತವೆ ಎಂಬುದನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ.",
    language: "en",
    subject: "Science",
    grade: "Grade 2",
    thumbnailUrl: "https://picsum.photos/seed/animals-habitat-wildlife/640/360",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    duration: 660,
    views: 1823,
    avgWatchDuration: 520,
    createdAt: "2026-03-10",
    tags: ["animals", "habitat", "science", "grade2"],
  },
  {
    id: "v8",
    title: "ಕನ್ನಡ ಕಥೆ - ಬಾನಾಡಿ ಮತ್ತು ಆಮೆ",
    titleHi: "कन्नड़ कहानी - खरगोश और कछुआ",
    titleKn: "ಕನ್ನಡ ಕಥೆ - ಮೊಲ ಮತ್ತು ಆಮೆ",
    description: "The classic story of the hare and tortoise in Kannada.",
    descriptionHi: "कन्नड़ में खरगोश और कछुए की क्लासिक कहानी।",
    descriptionKn: "ಕನ್ನಡದಲ್ಲಿ ಮೊಲ ಮತ್ತು ಆಮೆಯ ಪ್ರಸಿದ್ಧ ಕಥೆ.",
    language: "kn",
    subject: "Language Arts",
    grade: "Grade 2",
    thumbnailUrl: "https://picsum.photos/seed/story-hare-tortoise/640/360",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    duration: 480,
    views: 2109,
    avgWatchDuration: 395,
    createdAt: "2026-03-15",
    tags: ["story", "kannada", "fable", "grade2"],
  },
  {
    id: "v9",
    title: "Shapes All Around Us",
    titleHi: "हमारे आसपास आकार",
    titleKn: "ನಮ್ಮ ಸುತ್ತ ಆಕಾರಗಳು",
    description: "Identify circles, squares, triangles and more in everyday life.",
    descriptionHi: "रोजमर्रा की जिंदगी में वृत्त, वर्ग, त्रिभुज और अधिक पहचानें।",
    descriptionKn: "ದೈನಂದಿನ ಜೀವನದಲ್ಲಿ ವೃತ್ತ, ಚೌಕ, ತ್ರಿಕೋಣ ಮತ್ತು ಹೆಚ್ಚಿನದನ್ನು ಗುರುತಿಸಿ.",
    language: "en",
    subject: "Mathematics",
    grade: "Grade 1",
    thumbnailUrl: "https://picsum.photos/seed/math-shapes-geometry/640/360",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    duration: 420,
    views: 2567,
    avgWatchDuration: 340,
    createdAt: "2026-04-01",
    tags: ["shapes", "geometry", "math", "grade1"],
  },
  {
    id: "v10",
    title: "हमारा परिवार",
    titleHi: "हमारा परिवार",
    titleKn: "ನಮ್ಮ ಕುಟುಂಬ",
    description: "Learn about family members and relationships in Hindi.",
    descriptionHi: "हिंदी में परिवार के सदस्यों और संबंधों के बारे में जानें।",
    descriptionKn: "ಹಿಂದಿಯಲ್ಲಿ ಕುಟುಂಬದ ಸದಸ್ಯರು ಮತ್ತು ಸಂಬಂಧಗಳ ಬಗ್ಗೆ ತಿಳಿಯಿರಿ.",
    language: "hi",
    subject: "Social Studies",
    grade: "Grade 1",
    thumbnailUrl: "https://picsum.photos/seed/family-social-study/640/360",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    duration: 390,
    views: 1987,
    avgWatchDuration: 305,
    createdAt: "2026-04-08",
    tags: ["family", "hindi", "social", "grade1"],
  },
  {
    id: "v11",
    title: "Water Cycle",
    titleHi: "जल चक्र",
    titleKn: "ನೀರಿನ ಚಕ್ರ",
    description: "How water moves through evaporation, condensation, and precipitation.",
    descriptionHi: "वाष्पीकरण, संघनन और वर्षण के माध्यम से पानी कैसे चलता है।",
    descriptionKn: "ಆವಿಯಾಗುವಿಕೆ, ಘನೀಕರಣ ಮತ್ತು ಮಳೆಯ ಮೂಲಕ ನೀರು ಹೇಗೆ ಚಲಿಸುತ್ತದೆ.",
    language: "en",
    subject: "Science",
    grade: "Grade 4",
    thumbnailUrl: "https://picsum.photos/seed/water-cycle-rain-cloud/640/360",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    duration: 780,
    views: 1432,
    avgWatchDuration: 620,
    createdAt: "2026-04-15",
    tags: ["water", "cycle", "science", "grade4"],
  },
  {
    id: "v12",
    title: "ಕನ್ನಡ ಸಂಖ್ಯೆಗಳು",
    titleHi: "कन्नड़ संख्याएं",
    titleKn: "ಕನ್ನಡ ಸಂಖ್ಯೆಗಳು",
    description: "Learn numbers 1 to 100 in Kannada script.",
    descriptionHi: "कन्नड़ लिपि में 1 से 100 तक संख्याएं सीखें।",
    descriptionKn: "ಕನ್ನಡ ಲಿಪಿಯಲ್ಲಿ 1 ರಿಂದ 100 ರವರೆಗೆ ಸಂಖ್ಯೆಗಳನ್ನು ಕಲಿಯಿರಿ.",
    language: "kn",
    subject: "Mathematics",
    grade: "Grade 2",
    thumbnailUrl: "https://picsum.photos/seed/kannada-numbers-script/640/360",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    duration: 540,
    views: 2341,
    avgWatchDuration: 430,
    createdAt: "2026-05-01",
    tags: ["numbers", "kannada", "math", "grade2"],
  },
];

export const GAMES: Game[] = [
  {
    id: "g1",
    slug: "picture-puzzle",
    title: "Picture Puzzle",
    description: "Slide tiles to complete the picture. Trains spatial thinking and problem solving.",
    thumbnail: "https://picsum.photos/seed/puzzle-game-tiles/480/320",
    difficulty: "medium",
    ageRange: "6-10",
    plays: 4231,
    subjects: ["Mathematics", "Cognitive Skills"],
    languages: ["en", "hi", "kn"],
  },
  {
    id: "g2",
    slug: "word-matching",
    title: "Word Matching",
    description: "Match words across Kannada, Hindi and English. Builds multilingual vocabulary.",
    thumbnail: "https://picsum.photos/seed/word-match-language/480/320",
    difficulty: "easy",
    ageRange: "5-8",
    plays: 5812,
    subjects: ["Language Arts"],
    languages: ["en", "hi", "kn"],
  },
  {
    id: "g3",
    slug: "fruit-counter",
    title: "Fruit Counter",
    description: "Count the fruits on screen and select the right number. Fun arithmetic practice.",
    thumbnail: "https://picsum.photos/seed/fruits-counting-game/480/320",
    difficulty: "easy",
    ageRange: "4-7",
    plays: 6743,
    subjects: ["Mathematics"],
    languages: ["en", "hi", "kn"],
  },
  {
    id: "g4",
    slug: "color-sort",
    title: "Color Sort",
    description: "Drag and drop colored objects into the matching buckets. Improves color recognition.",
    thumbnail: "https://picsum.photos/seed/color-sort-buckets/480/320",
    difficulty: "easy",
    ageRange: "4-6",
    plays: 3987,
    subjects: ["Art & Craft", "Cognitive Skills"],
    languages: ["en", "hi", "kn"],
  },
  {
    id: "g5",
    slug: "letter-scramble",
    title: "Letter Scramble",
    description: "Unscramble the jumbled letters to form the correct word. Great for spelling practice.",
    thumbnail: "https://picsum.photos/seed/scramble-letters-word/480/320",
    difficulty: "medium",
    ageRange: "7-12",
    plays: 3214,
    subjects: ["Language Arts"],
    languages: ["en", "hi", "kn"],
  },
];

export const ANALYTICS: AnalyticsData = {
  totalVideoViews: 32425,
  totalGamePlays: 23987,
  avgWatchDuration: 428,
  topVideos: VIDEOS.slice(0, 5).sort((a, b) => b.views - a.views),
  topGames: GAMES.sort((a, b) => b.plays - a.plays).slice(0, 3),
  viewsByLanguage: { en: 18432, hi: 8124, kn: 5869 },
  recentActivity: [
    { type: "video_view", itemId: "v3", itemTitle: "ಕನ್ನಡ ಅಕ್ಷರಮಾಲೆ", timestamp: "2026-09-02T14:23:00Z", language: "kn" },
    { type: "game_play", itemId: "g3", itemTitle: "Fruit Counter", timestamp: "2026-09-02T14:18:00Z", language: "en" },
    { type: "video_view", itemId: "v1", itemTitle: "Counting Numbers 1 to 20", timestamp: "2026-09-02T14:12:00Z", language: "en" },
    { type: "game_play", itemId: "g2", itemTitle: "Word Matching", timestamp: "2026-09-02T14:05:00Z", language: "hi" },
    { type: "video_view", itemId: "v4", itemTitle: "हिंदी वर्णमाला", timestamp: "2026-09-02T13:58:00Z", language: "hi" },
  ],
};

export function getVideoTitle(video: Video, lang: Language): string {
  if (lang === "hi" && video.titleHi) return video.titleHi;
  if (lang === "kn" && video.titleKn) return video.titleKn;
  return video.title;
}

export function getVideoDescription(video: Video, lang: Language): string {
  if (lang === "hi" && video.descriptionHi) return video.descriptionHi;
  if (lang === "kn" && video.descriptionKn) return video.descriptionKn;
  return video.description;
}

export function formatDuration(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}:${s.toString().padStart(2, "0")}`;
}

export function formatViews(views: number): string {
  if (views >= 1000) return `${(views / 1000).toFixed(1)}k`;
  return views.toString();
}
